### ISSUE TITLE
Overly high JS baseline requirement, from using URL.canParse()

### ISSUE THREAD

**Issue by Tristan971** [braintree/sanitize-url#78]
Hello,

In here, the library has begun using URL.canParse():

https://github.com/braintree/sanitize-url/blame/cdd33eb72e9f56eff7b3c49f1c5ed133838b9956/src/index.ts#L24

This imposes a surprisingly strict requirement on browser versions:
- Safari/iOS 17.0
- Firefox 125
- Chromium 120

As far as I can tell, it has as a result only been widely available since ~ December 2023.

I don't mind it necessarily, but it is a huge enough jump that I'd suggest making it in a major version update.

I'm not sure what the previous minimal browser version set was exactly, but at least up to iOS 14 worked, going by the browsers we had successfully tested on our own website.

**Comment by akphi** [comment]
though rather unrelated, I would like to mention that this makes testing with [Jest](https://jestjs.io/) a little less convenient since `URL.canParse` is not implemented in [jsdom](https://github.com/jsdom/jsdom)

**Comment by erquhart** [comment]
This also breaks compatibility with React Native.

**Comment by ibooker** [comment]
Hello, 
@Tristan971 Thanks for reporting this issue with `URL.canParse()`. We'll take a closer look at this issue.  (Internal Tracking: BTWEB-171)

@erquhart We do not specifically support compatibility with React Native.  If you can provides some details about what no longer works, we can better understand if its something we can address.

**Comment by erquhart** [comment]
@ibooker I don't see anything in the repo stating explicit support for any platform, browser etc., I'm just adding React Native to the list of environments for which this library no longer works.

I don't have a separate issue to outline, just that the use `URL.canParse()` is not supported in React Native, as well as a fair amount of browser versions and jsdom, as mentioned by others.

**Comment by chrisvanpatten** [comment]
Agree, 7.1.0 should have been released as 8.0.0; effectively dropping support for older Nodes, whether intentional or not, is a breaking change.

**Comment by patocallaghan** [comment]
@ibooker just wondering if there will be a newer version of 7.x which will ship without the`URL.canParse` change? I see some new releases have shipped but we can't upgrade due to our browser support. We could use patch package but would rather only do that as a last resort.

**Comment by samuel871211** [comment]
Workaround:

core-js provides a polyfill for `URL.canParse`
https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/web.url.can-parse.js
I'm currently configuring in my webpack.

**Comment by wenny-chang** [comment]
Hi, I've encountered the same question, but I'm using react-app v17.0.1 with jest, is there any solution could fix this?
version: `@braintree/sanitize-url: "^7.1.1"`
``` bash
  TypeError: URL.canParse is not a function
  ...
   at isValidUrl (node_modules/@braintree/sanitize-url/dist/index.js:15:16)
   at sanitizeUrl (node_modules/@braintree/sanitize-url/dist/index.js:71:14)
```
